name: weepy
description: File sharing over wifi.
publish_to: 'none'
version: 0.1.1+4

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  http_parser: ^4.0.2
  media_store_plus: ^0.0.7
  mime: ^1.0.4
  network_info_plus: ^4.0.0
  path: ^1.8.2
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  shelf: ^1.4.1
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  open_filex: ^4.3.2
  sqlite3_flutter_libs: ^0.5.15
  network_tools: ^3.2.1
  shared_preferences: ^2.1.2
  lottie: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_crashlytics: ^3.3.4
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "assets/lottie/"