name: BuildTask

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - docs/**
      - screenshots**
      - test/**
      - LICENSE
      - README.md
      - GitVersion.yml
      - .vscode/**
      - .github/**
      - whatsnew/*

jobs:
  build_android:

    runs-on: ubuntu-latest
    needs: version

    steps:

      - uses: actions/checkout@v3
      
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      
      - name: Update version in pubpsec.yaml
        run: sed -i 's/1.0.0+1/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
      
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
 
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Running flutter tests
        run: flutter test
  
      - name: Start appbundle build
        run: flutter build appbundle
        
      - name: Start apk build
        run: flutter build apk

      - name: Uploading android packages
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error

  build_linux:
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      
      - name: Update version in pubpsec.yaml
        run: sed -i 's/1.0.0+1/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
        
      - name: Update version in debian.yaml
        run: sed -i 's/1.0.0/${{ steps.version.outputs.content }}/g' debian/debian.yaml

      - name: Update version in FileDrop.desktop
        run: sed -i 's/1.0.0/${{ steps.version.outputs.content }}/g' debian/gui/FileDrop.desktop

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get flutter_to_debian
        run: dart pub global activate -s git https://github.com/iamalper/flutter_to_debian
    
      - name: Preparing for linux build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter config --enable-linux-desktop

      - name: Running flutter tests
        run: flutter test

      - name: Start linux build
        run: flutter build linux

      - name: Run flutter_to_debian
        run: flutter_to_debian

      - name: Upload deb package
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            build/linux/x64/release/debian/*.deb
            build/linux/x64/release/bundle
          if-no-files-found: error

  build_windows:
    runs-on: windows-latest
    needs: version
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - uses: actions/checkout@v3
      
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      
      - name: Update version in pubpsec.yaml
        run: sed -i 's/1.0.0+1/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml

      - run: flutter config --enable-windows-desktop

      - name: Running flutter tests
        run: flutter test

      - name: Build for windows
        run: flutter build windows

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            build\windows\runner\Release
          if-no-files-found: error

  release:
    env:
      isRelease: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: [build_android, build_linux, version, build_windows]
    steps:
      - uses: actions/checkout@v3

      - name: Downloading builds
        uses: actions/download-artifact@v3

      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt

      - name: Releasing builds
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          automatic_release_tag: "v${{ steps.version.outputs.content }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ env.isRelease == 'false' }}
          files: | 
            android/flutter-apk/app-release.apk
            android/bundle/release/app-release.aab
            linux/*.deb
            windows

  version:
    name: Create version number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Create version.txt with MajorMinorPatch
        run: echo ${{ steps.gitversion.outputs.MajorMinorPatch }}${{ steps.gitversion.outputs.PreReleaseTagWithDash }} > version_nw.txt

      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version_nw.txt > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt

  google_play_publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: [release]
    steps:
    - uses: actions/checkout@v2
    - name: Downloading builds
      uses: actions/download-artifact@v3
      with: 
         name: builds

    - name: Publishing
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT }}
        packageName: com.alper.weepy
        releaseFiles: bundle/release/app-release.aab
        track: beta
        whatsNewDirectory: whatsnew